### PR TITLE
chore: fix CodeClimate suggestions

### LINKED ISSUE #33: Ruby Specific CodeClimate Suggestions
#### Issue Summary

There are a couple issues reported by CodeClimate:

- Freeze mutable objects assigned to constants. NEW
- Use alias instead of alias_method in a class body.
- Favor a normal if-statement over a modifier clause in a multiline statement. 

Note: `The .length > 0` items reported are covered by another github issue. 

#### Acceptance Criteria
- the issues reported above in this issue are resolved. There may be other issues, they will not block your PR from being merged.

### PR DESCRIPTION
**Pull request by valterbarros**
Fixes #33 

- Shift-multiline-ifs-to-single-line-if
- Change if .length > 0 to unless .empty?
- Change alias_method to alias

PS: I know that .lenght > 0 issue is already solved, but I do a modification using the unless .empty? to increase the solution and make it more idiomatic.

Signed-off-by: ValterBarros <valterinside@gmail.com>

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/smtpapi-ruby?pullRequest=36) <br/>All committers have signed the CLA.

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/smtpapi-ruby?pullRequest=36) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/smtpapi-ruby?pullRequest=36) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/smtpapi-ruby?pullRequest=36) it.</sub>

**Comment by valterbarros** [comment]
closes #33

**Comment by valterbarros** [comment]
I already accept the CLA.

**Comment by mbernier** [comment]
@valterbarros

We have not been able to merge your Pull Request, but because you are awesome - we wanted to make sure you could still get a SendGrid Hacktoberfest shirt.  

Please go **fill [out our swag form](https://dx.sendgrid.com/swag) before Nov 5th** and we will send the shirt! (We know that you might have tried this before and it didn’t work, sorry about that!)

### **You have till Nov 5th to fill out this form** in order to get the Hacktoberfest shirt!

Thank you for contributing during Hacktoberfest! We hope to see you in the repos soon! Just so you know, we always give away a SendGrid shirt for your first ever non-Hacktoberfest PR that gets merged.

**Review by childish-sambino — APPROVED** [review]

**Pull request merged**
