### PR TITLE
Remove redundant if clause

### LINKED ISSUE #49: Fix "method_complexity" issue in lib/smtpapi.rb
Method `escape_unicode` has a Cognitive Complexity of 7 (exceeds 5 allowed). Consider refactoring.

https://codeclimate.com/github/sendgrid/smtpapi-ruby/lib/smtpapi.rb#issue_59f66996439acf0001000016

### PR DESCRIPTION
**Pull request by iamsuganthi**
This check is not necessary in line 147 since it is already checked in line 145.
Fixes #49

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/smtpapi-ruby?pullRequest=53) <br/>All committers have signed the CLA.

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/smtpapi-ruby?pullRequest=53) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/smtpapi-ruby?pullRequest=53) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/smtpapi-ruby?pullRequest=53) it.</sub>

**Comment by mbernier** [comment]
Why did you close this PR?

**Comment by thinkingserious** [comment]
@enthudrives

We have not been able to merge your Pull Request, but because you are awesome - we wanted to make sure you could still get a SendGrid Hacktoberfest shirt.  

Please go **fill [out our swag form](https://dx.sendgrid.com/swag) before Nov 5th** and we will send the shirt! (We know that you might have tried this before and it didn’t work, sorry about that!)

### **You have till Nov 5th to fill out this form** in order to get the Hacktoberfest shirt!

Thank you for contributing during Hacktoberfest! We hope to see you in the repos soon! Just so you know, we always give away a SendGrid shirt for your first ever non-Hacktoberfest PR that gets merged.

**Comment by iamsuganthi** [comment]
Hi Matt,
I closed this PR as it was polluted by another commit that I made for
SimpleCov.
Recreated another PR for the same issue. (#55)
Please take a look at that.

**Comment by iamsuganthi** [comment]
Ah. Just saw that you reopened this PR. Thanks for doing that.

@thinkingserious  On a side note, I'm not able to fill the swag form. :(
I've sent an email to dx@sendgrid.com

**Comment by thinkingserious** [comment]
Hi @enthudrives,

Could you please try the [swag form](https://dx.sendgrid.com/swag) again? Note that you must be logged into your @enthudrives GitHub account.

Thanks!

With Best Regards,

Elmer

**Comment by iamsuganthi** [comment]
@thinkingserious That worked. Thanks 👍

**Comment by childish-sambino** [comment]
Duplicate of #55

**Pull request closed without merging**
