### PR TITLE
[Closes #48] Reduce cognitive complexity on #to_array

### LINKED ISSUE #48: Fix "method_complexity" issue in lib/smtpapi.rb
Method `to_array` has a Cognitive Complexity of 13 (exceeds 5 allowed). Consider refactoring.

https://codeclimate.com/github/sendgrid/smtpapi-ruby/lib/smtpapi.rb#issue_59f66996439acf0001000015

### PR DESCRIPTION
**Pull request by lauratpa**
Closes #48 and #32 

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
Reduce cognitive complexity of `Smtpapi#to_array`

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/smtpapi-ruby?pullRequest=51) <br/>All committers have signed the CLA.

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/smtpapi-ruby?pullRequest=51) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/smtpapi-ruby?pullRequest=51) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/smtpapi-ruby?pullRequest=51) it.</sub>

**Comment by lauratpa** [comment]
https://codeclimate.com/github/sendgrid/smtpapi-ruby/pull/51

**Comment by thinkingserious** [comment]
Hello @jekuta,

Was there a problem with this PR?

Thanks!

With Best Regards,

Elmer

**Pull request closed without merging**
