### PR TITLE
chore: Resolve linting issues.

### LINKED ISSUE #63: Small fixes for clarity and readability
#### Issue Summary

These issues should be relatively easy to fix up, whether you are new to Ruby or just want to practice! 

```
examples/example.rb:7:1: C: Missing space after #.
#header.add_to(['test1@example.com', 'test2@example.com'])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
examples/example.rb:10:1: C: Missing space after #.
#header.set_tos(['you@youremail.com', 'other@otheremail.com']) # to => ['you@youremail.com', 'other@otheremail.com']
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
examples/example.rb:10:81: C: Line is too long. [116/80]
#header.set_tos(['you@youremail.com', 'other@otheremail.com']) # to => ['you@youremail.com', 'other@otheremail.com']
                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
examples/example.rb:14:34: C: Use %w or %W for array of words.
header.add_substitution('other', ['one', 'two'])   # sub = {keep: ['secret'], other: ['one', 'two']}
                                 ^^^^^^^^^^^^^^
examples/example.rb:14:81: C: Line is too long. [100/80]
header.add_substitution('other', ['one', 'two'])   # sub = {keep: ['secret'], other: ['one', 'two']}
                                                                                ^^^^^^^^^^^^^^^^^^^^
examples/example.rb:19:1: C: Extra blank line detected.
examples/example.rb:23:1: C: Extra blank line detected.
examples/example.rb:25:1: C: Missing space after #.
#header.set_unique_args({'cow' => 'chicken'})
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
examples/example.rb:26:1: C: Missing space after #.
#header.set_unique_args({'dad' => 'proud'})
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
examples/example.rb:33:1: C: Missing space after #.
#header.set_categories(['tactics', 'advanced']) # category = ['tactics', 'advanced']
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
examples/example.rb:33:81: C: Line is too long. [84/80]
#header.set_categories(['tactics', 'advanced']) # category = ['tactics', 'advanced']
                                                                                ^^^^
examples/example.rb:35:1: C: Extra blank line detected.
examples/example.rb:41:1: C: Missing space after #.
#header.set_sections({'-charge-' => 'This ship is useless.'})
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
examples/example.rb:43:1: C: Extra blank line detected.
examples/example.rb:49:1: C: Do not use block comments.
=begin
^^^^^^
examples/example.rb:66:1: C: Do not use block comments.
=begin
^^^^^^
examples/example.rb:74:108: C: Line is too long. [124/80]
# This is to specify an [ASM Group](https://sendgrid.com/docs/User_Guide/advanced_suppression_manager.html) for the message.
                                                                                                           ^^^^^^^^^^^^^^^^^
examples/example.rb:79:20: C: Prefer single-quoted strings when you don't need string interpolation or special symbols.
header.set_ip_pool("test_pool")
                   ^^^^^^^^^^^
examples/example.rb:81:21: C: Final newline missing.
print header.to_json
                    
lib/smtpapi.rb:119:7: C: Favor unless over if for negative conditions.
      data['to'] = @to if @to.!empty?
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/smtpapi.rb:120:7: C: Favor unless over if for negative conditions.
      data['sub'] = @sub if @sub.!empty?
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/smtpapi.rb:121:7: C: Favor unless over if for negative conditions.
      data['section'] = @section if @section.!empty?
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/smtpapi.rb:122:7: C: Favor unless over if for negative conditions.
      data['unique_args'] = @unique_args if @unique_args.!empty?
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/smtpapi.rb:123:7: C: Favor unless over if for negative conditions.
      data['category'] = @category if @category.!empty?
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/smtpapi.rb:124:7: C: Favor unless over if for negative conditions.
      data['filters'] = @filters if @filters.!empty?
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/smtpapi.rb:132:7: C: Favor unless over if for negative conditions.
      data['send_each_at'] = str_each_at if str_each_at.!empty?
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### PR DESCRIPTION
**Pull request by mrala**
Resolves #63.

- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

- Clean up rubopcop issues

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/smtpapi-ruby?pullRequest=64) <br/>All committers have signed the CLA.

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/smtpapi-ruby?pullRequest=64) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/smtpapi-ruby?pullRequest=64) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/smtpapi-ruby?pullRequest=64) it.</sub>

**Comment by thinkingserious** [comment]
Hello @mrala,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/hacktoberfest/join">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by mrala** [comment]
Not a problem, @thinkingserious! Just a heads up, I believe this also resolves #60.

**Comment by thinkingserious** [comment]
Awesome, thanks for the heads up @mrala!

**Comment by thinkingserious** [comment]
Hello @mrala,<br /><br/>Thanks again for the PR!<br /><br />                                         We noticed that you have earned 3 out of the 5 points needed to receive glorious SendGrid Hacktoberfest swag.<br /><br />                                         Please take a moment to checkout <a href="https://dx.sendgrid.com/hacktoberfest/issues">this link</a> to find more issues to get you past the required threshold.<br /><br />                                         Also, please be sure that you have officially registered <a href="https://dx.sendgrid.com/hacktoberfest/join">here</a>.<br /><br />                                         Thank you and Happy Hacktobering!<br /><br />                                         Team SendGrid DX

**Comment by thinkingserious** [comment]
Hello @mrala,<br /><br/>Thanks again for the PR!<br /><br />                                         You have earned 3 out of the 5 points needed to receive glorious SendGrid Hacktoberfest swag.<br /><br />                                         Please take a moment to checkout <a href="https://dx.sendgrid.com/hacktoberfest/issues">this link</a> to find more issues to get you past the required threshold or to simply continue the celebration.<br /><br />                                         Also, <strong>please be sure you have officially registered with us <a href="https://dx.sendgrid.com/hacktoberfest/join">here</a> by November 1, 2018</strong> to qualify.<br /><br />                                         If you have any questions you can email us at <a href="mailto:dx+hacktoberfest2018@sendgrid.com">dx+hacktoberfest2018@sendgrid.com</a>.<br /><br />                                         Thank you and Happy Hacktobering!<br /><br />                                         Team SendGrid

**Pull request merged**
