### PR TITLE
chore: Added .codeclimate.yml

### PR DESCRIPTION
**Pull request by veruz**
Closes Issue #30

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/smtpapi-ruby?pullRequest=31) <br/>All committers have signed the CLA.

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/smtpapi-ruby?pullRequest=31) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/smtpapi-ruby?pullRequest=31) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/smtpapi-ruby?pullRequest=31) it.</sub>

**Comment by veruz** [comment]
It seems that the .codeclimate.yml is working correctly and pointing out issues that rubocop found. Achieved by cloning the repo and using a docker/codeclimate init on it to generate the file.

**Comment by mbernier** [comment]
Yep, that is expected! We won't be blocking for these fixes, but rather making issues for them ;)

**Comment by thinkingserious** [comment]
Hello @veruz,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
